export const STORAGE_PREFIX = "VLUI:" as const;

export const ALL_STORAGE_KEYS = [
  "AUTOCOMPLETE",
  "TIMEZONE",
  "DISABLED_DEFAULT_TIMEZONE",
  "THEME",
  "FAVICON_COLOR",
  "LOGS_LIMIT",
  "LOGS_MARKDOWN",
  "LOGS_ANSI",
  "LOGS_DISABLED_HOVERS",
  "LOGS_QUERY_HISTORY",
  "SERVER_URL",
  "RAW_JSON_LIVE_VIEW",
  "LOGS_OVERRIDE_TIME",
  "LOGS_TABLE_DRAWER",
  "LOGS_FILTER_SIDEBAR_WIDTH",
  "LOGS_FILTER_SIDEBAR_HIDDEN",
  "LOGS_DISABLED_LEVEL_DETECTION"
] as const;

export const TABLE_KEYS = {
  COLS_PREFS: "LOGS_TABLE_COLS_PREFS",
  COLS_VIEW: "LOGS_TABLE_COLS_VIEW",
} as const;

